spring:
  application:
    name: ms-account
h2: 
    console:
        enabled: true
server:
    port: 9092
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
        leaseRenewalIntervalInSeconds: 4
        leaseExpirationDurationInSeconds: 8
